export enum AuthActionType {
    USER_SIGNED_IN = 'USER_SIGNED_IN',
    USER_SIGNED_OUT = 'USER_SIGNED_OUT',
    USER_FETCHED = 'USER_FETCHED',
    USER_UPDATED = 'USER_UPDATED',
    USER_UPDATED_EMAIL = 'USER_UPDATED_EMAIL',
}

export const DISPLAY_NAME_MAX_LENGTH = 20;
