// -- Constants

export enum PokerTableActionType {
    REQUEST_CREATE_POKER_TABLE = 'REQUEST_CREATE_POKER_TABLE',
    RECEIVE_CREATED_POKER_TABLE = 'RECEIVE_CREATED_POKER_TABLE',
    REQUEST_SUBSCRIBE_TO_POKER_TABLE = 'REQUEST_SUBSCRIBE_TO_POKER_TABLE',
    RECEIVE_SUBSCRIBE_TO_POKER_TABLE = 'RECEIVE_SUBSCRIBE_TO_POKER_TABLE',
    RECEIVE_POKER_TABLE_PLAYERS_CHANGE = 'RECEIVE_POKER_TABLE_PLAYERS_CHANGE',
    RECEIVE_POKER_TABLE_DATA_CHANGE = 'RECEIVE_POKER_TABLE_DATA_CHANGE',
    UNSUBSCRIBE_TO_POKER_TABLE = 'UNSUBSCRIBE_TO_POKER_TABLE',
}

export const DEFAULT_DISPLAY_NAME = 'Anonymous';
export const DEFAULT_GAME_NAME = 'Planning poker game';
export const DEFAULT_CARD_LIST = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];
